### ISSUE TITLE
ValueError: dictionary update sequence element #4 has length 1; 2 is required

### ISSUE THREAD

**Issue by GoogleCodeExporter** [halamalala/inkscape2tikz#54]
```
What steps will reproduce the problem?

1. Run the tikz export on the attached svg

What is the expected output? What do you see instead?

the tikz file to be produced, instead the following error is reported:


Traceback (most recent call last):
  File "tikz_export.py", line 1391, in <module>
    main_inkscape()
  File "tikz_export.py", line 1379, in main_inkscape
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 215, in affect
    self.effect()
  File "tikz_export.py", line 1286, in effect
    s = self._output_group(nodes, graphics_state)
  File "tikz_export.py", line 1253, in _output_group
    s += self._handle_group(node, graphics_state, accumulated_state)
  File "tikz_export.py", line 944, in _handle_group
    code = self._output_group(groupnode, accumulated_state.accumulate(graphics_state))
  File "tikz_export.py", line 1231, in _output_group
    graphics_state = GraphicsState(node)
  File "tikz_export.py", line 523, in __init__
    self._get_graphics_state(svg_node)
  File "tikz_export.py", line 528, in _get_graphics_state
    style = parse_style(node.get('style', ''))
  File "tikz_export.py", line 503, in parse_style
    return dict([map(string.strip, i.split(":")) for i in s.split(";") if len(i)])
ValueError: dictionary update sequence element #4 has length 1; 2 is required


What version of the product are you using? On what operating system?

Version downloaded from the front page links.

Inkscape 0.48.4 r9939 (Jul 30 2013)

Please provide any additional information below.

This svg was first produced by exporting an xfig figure to svg. 

```

Original issue reported on code.google.com by `crobarcr...@gmail.com` on 30 Jan 2014 at 10:41

Attachments:
- [newton.svg](https://storage.googleapis.com/google-code-attachments/inkscape2tikz/issue-54/comment-0/newton.svg)

**Comment by GoogleCodeExporter** [comment]
```
Incidentally, I have found making virtually any small change to the file in 
inkscape is enough to make it work (even if I don't save the change). This also 
works the same way if I open the original .fig file in inkscape.
```

Original comment by `crobarcr...@gmail.com` on 30 Jan 2014 at 11:15

**Comment by GoogleCodeExporter** [comment]
```
Not able to reproduce this. If it is still an issue, open a new one at 
https://github.com/kjellmf/svg2tikz/issues
```

Original comment by `kjel...@gmail.com` on 23 May 2014 at 7:39
- Changed state: **WontFix**
