### ISSUE TITLE
unittouu not part of inkex module. 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [halamalala/inkscape2tikz#55]
```
What steps will reproduce the problem?
1. Not sure why it is happening

What is the expected output? What do you see instead?
Trying to convert svg to tikz. Getting the following error
Traceback (most recent call last):
  File "tikz_export.py", line 1391, in <module>
    main_inkscape()
  File "tikz_export.py", line 1379, in main_inkscape
    effect.affect()
  File "/home/ssadasiv/.config/inkscape/extensions/inkex.py", line 261, in affect
    self.effect()
  File "tikz_export.py", line 1286, in effect
    s = self._output_group(nodes, graphics_state)
  File "tikz_export.py", line 1245, in _output_group
    shapedata, options = self._handle_shape(node)
  File "tikz_export.py", line 1037, in _handle_shape
    center = map(inkex.unittouu, [node.get('cx', '0'), node.get('cy', '0')])
AttributeError: 'module' object has no attribute 'unittouu'

What version of the product are you using? On what operating system?
inkscape devel on ubuntu-13.10 

Subramanya 
Please provide any additional information below.


```

Original issue reported on code.google.com by `subraman...@gmail.com` on 17 Apr 2014 at 5:37

**Comment by GoogleCodeExporter** [comment]
```
See https://github.com/kjellmf/svg2tikz/issues/17
```

Original comment by `kjel...@gmail.com` on 21 May 2014 at 7:14
- Changed state: **Transferred**
